#!/usr/bin/env ruby
$LOAD_PATH << File.join(File.dirname(__FILE__), 'lib')

require "yaml"
require "users"

Users.load_old
new_users = {}
Users.users.each do |user|
  new_users[user.name] = user.password
end

File.open "users", 'w' do |out|
  YAML.dump new_users, out
end
