#!/usr/bin/env ruby

$LOAD_PATH << File.join(File.dirname(__FILE__), 'lib')

require "users"

Users.loadusers

Users.usercoll.drop
puts Users.usercoll.create_index 'name', [:unique => true]
Users.users.each do |user, pwdhash|
  Users.usercoll.insert('name' => user, 'pwdhash' => pwdhash.inspect)
end
Users.usercoll.find.each do |userinfo|
  puts userinfo.inspect
end
