#!/usr/bin/env ruby

require 'lib/users'

Users::initialize
if Users::adduser("ojosa","password") == false
  puts "User exists"
else
  puts "User added"
end

puts "username: "
name = gets
puts "password: "
pass = gets

if Users::login(name, pass) == true
  puts "Success"
else
  puts "Failure"
end


Users::dump
